---
- name: ACL
  hosts: csr1
  gather_facts: false
  connection: network_cli

  tasks:

    - name: extended ACL om ftp en telnet verkeer te blokkeren
      ios_config:
        lines:
          - access-list 110 deny tcp any any eq 20
          - access-list 110 deny tcp any any eq 23
          - access-list 110 permit ip any any
        parents: ip access-list extended Services_List

    - name: ACL op interface
      ios_config:
        lines:
          - ip access-group 110 in
        parents: interface GigabitEthernet 2
