---
- name: DHCP Configuration
  hosts: csr2
  gather_facts: false 
  connection: network_cli
  tasks:

    - name: Configure DHCP Pool
      ios_config:
        lines:
          - ip dhcp pool test
          - ip dhcp excluded-address 192.168.20.1 192.168.20.100

    - name: Configure DHCP Settings
      ios_config:
        lines:
          - network 192.168.20.0 255.255.255.0
          - default-router 192.168.20.254
          - dns-server 8.8.8.8
        parents: ip dhcp pool test
